#!/usr/bin/perl
use strict;
use warnings;

my $asd = 'AASDASDASDFGAGASFAWEDEDCASSDFARFRFASFAWFAFASDFASFASDFASDFFFFFFFFFFFFFFFFFFFSSSSSSSSSSSSSSSSSSSSSSSSSSSSDDDDDDDDDDDDDDDDDDDDDF';

$asd =~ /D.*A$/s;
 
print($asd,"\n");
